// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Result of `getRequestStatusForAuthorization`.
enum HkRequestStatus: Int, CaseIterable {
  /// Status unknown (error or not available).
  case unknown = 0
  /// The dialog has never been shown for at least one type.
  case shouldRequest = 1
  /// The dialog has already been shown for all types.
  case unnecessary = 2
}

/// Result of `authorizationStatus(for:)` (only write access can be queried).
enum HkWriteStatus: Int, CaseIterable {
  case notDetermined = 0
  case sharingDenied = 1
  case sharingAuthorized = 2
  case unknown = 3
}

/// Source of a sample (`HKSourceRevision`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct HkSource: Hashable, CustomStringConvertible {
  var bundleId: String
  var name: String
  var version: String? = nil
  var productType: String? = nil
  var operatingSystemVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HkSource? {
    let bundleId = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let version: String? = nilOrValue(pigeonVar_list[2])
    let productType: String? = nilOrValue(pigeonVar_list[3])
    let operatingSystemVersion: String? = nilOrValue(pigeonVar_list[4])

    return HkSource(
      bundleId: bundleId,
      name: name,
      version: version,
      productType: productType,
      operatingSystemVersion: operatingSystemVersion
    )
  }
  func toList() -> [Any?] {
    return [
      bundleId,
      name,
      version,
      productType,
      operatingSystemVersion,
    ]
  }
  static func == (lhs: HkSource, rhs: HkSource) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.bundleId, rhs.bundleId) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.version, rhs.version) && MessagesPigeonInternal.deepEquals(lhs.productType, rhs.productType) && MessagesPigeonInternal.deepEquals(lhs.operatingSystemVersion, rhs.operatingSystemVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HkSource")
    MessagesPigeonInternal.deepHash(value: bundleId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: version, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: productType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: operatingSystemVersion, hasher: &hasher)
  }

  public var description: String {
    return "HkSource(bundleId: \(String(describing: bundleId)), name: \(String(describing: name)), version: \(String(describing: version)), productType: \(String(describing: productType)), operatingSystemVersion: \(String(describing: operatingSystemVersion)))"
  }
}

/// Measuring device (`HKDevice`), all fields optional.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HkDevice: Hashable, CustomStringConvertible {
  var name: String? = nil
  var model: String? = nil
  var manufacturer: String? = nil
  var hardwareVersion: String? = nil
  var firmwareVersion: String? = nil
  var softwareVersion: String? = nil
  var localIdentifier: String? = nil
  var udiDeviceIdentifier: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HkDevice? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let model: String? = nilOrValue(pigeonVar_list[1])
    let manufacturer: String? = nilOrValue(pigeonVar_list[2])
    let hardwareVersion: String? = nilOrValue(pigeonVar_list[3])
    let firmwareVersion: String? = nilOrValue(pigeonVar_list[4])
    let softwareVersion: String? = nilOrValue(pigeonVar_list[5])
    let localIdentifier: String? = nilOrValue(pigeonVar_list[6])
    let udiDeviceIdentifier: String? = nilOrValue(pigeonVar_list[7])

    return HkDevice(
      name: name,
      model: model,
      manufacturer: manufacturer,
      hardwareVersion: hardwareVersion,
      firmwareVersion: firmwareVersion,
      softwareVersion: softwareVersion,
      localIdentifier: localIdentifier,
      udiDeviceIdentifier: udiDeviceIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      model,
      manufacturer,
      hardwareVersion,
      firmwareVersion,
      softwareVersion,
      localIdentifier,
      udiDeviceIdentifier,
    ]
  }
  static func == (lhs: HkDevice, rhs: HkDevice) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && MessagesPigeonInternal.deepEquals(lhs.manufacturer, rhs.manufacturer) && MessagesPigeonInternal.deepEquals(lhs.hardwareVersion, rhs.hardwareVersion) && MessagesPigeonInternal.deepEquals(lhs.firmwareVersion, rhs.firmwareVersion) && MessagesPigeonInternal.deepEquals(lhs.softwareVersion, rhs.softwareVersion) && MessagesPigeonInternal.deepEquals(lhs.localIdentifier, rhs.localIdentifier) && MessagesPigeonInternal.deepEquals(lhs.udiDeviceIdentifier, rhs.udiDeviceIdentifier)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HkDevice")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: manufacturer, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hardwareVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: firmwareVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: softwareVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: localIdentifier, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: udiDeviceIdentifier, hasher: &hasher)
  }

  public var description: String {
    return "HkDevice(name: \(String(describing: name)), model: \(String(describing: model)), manufacturer: \(String(describing: manufacturer)), hardwareVersion: \(String(describing: hardwareVersion)), firmwareVersion: \(String(describing: firmwareVersion)), softwareVersion: \(String(describing: softwareVersion)), localIdentifier: \(String(describing: localIdentifier)), udiDeviceIdentifier: \(String(describing: udiDeviceIdentifier)))"
  }
}

/// Blood pressure from an `HKCorrelation` (mmHg).
///
/// Generated class from Pigeon that represents data sent in messages.
struct HkBloodPressure: Hashable, CustomStringConvertible {
  var systolic: Double
  var diastolic: Double
  var systolicUuid: String? = nil
  var diastolicUuid: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HkBloodPressure? {
    let systolic = pigeonVar_list[0] as! Double
    let diastolic = pigeonVar_list[1] as! Double
    let systolicUuid: String? = nilOrValue(pigeonVar_list[2])
    let diastolicUuid: String? = nilOrValue(pigeonVar_list[3])

    return HkBloodPressure(
      systolic: systolic,
      diastolic: diastolic,
      systolicUuid: systolicUuid,
      diastolicUuid: diastolicUuid
    )
  }
  func toList() -> [Any?] {
    return [
      systolic,
      diastolic,
      systolicUuid,
      diastolicUuid,
    ]
  }
  static func == (lhs: HkBloodPressure, rhs: HkBloodPressure) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.systolic, rhs.systolic) && MessagesPigeonInternal.deepEquals(lhs.diastolic, rhs.diastolic) && MessagesPigeonInternal.deepEquals(lhs.systolicUuid, rhs.systolicUuid) && MessagesPigeonInternal.deepEquals(lhs.diastolicUuid, rhs.diastolicUuid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HkBloodPressure")
    MessagesPigeonInternal.deepHash(value: systolic, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: diastolic, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: systolicUuid, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: diastolicUuid, hasher: &hasher)
  }

  public var description: String {
    return "HkBloodPressure(systolic: \(String(describing: systolic)), diastolic: \(String(describing: diastolic)), systolicUuid: \(String(describing: systolicUuid)), diastolicUuid: \(String(describing: diastolicUuid)))"
  }
}

/// A sample that was read. For blood pressure, `uuid` is the UUID of the
/// correlation, `value` is null and `bloodPressure` is set.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HkSample: Hashable, CustomStringConvertible {
  var uuid: String
  var type: String
  var startMs: Int64
  var endMs: Int64
  /// Value in the fixed plugin unit of the type (see `unit`).
  var value: Double? = nil
  var unit: String? = nil
  var bloodPressure: HkBloodPressure? = nil
  var source: HkSource
  var device: HkDevice? = nil
  /// HealthKit metadata: strings, numbers, bools; dates as ms since epoch,
  /// quantities as text.
  var metadata: [String?: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HkSample? {
    let uuid = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! String
    let startMs = pigeonVar_list[2] as! Int64
    let endMs = pigeonVar_list[3] as! Int64
    let value: Double? = nilOrValue(pigeonVar_list[4])
    let unit: String? = nilOrValue(pigeonVar_list[5])
    let bloodPressure: HkBloodPressure? = nilOrValue(pigeonVar_list[6])
    let source = pigeonVar_list[7] as! HkSource
    let device: HkDevice? = nilOrValue(pigeonVar_list[8])
    let metadata = pigeonVar_list[9] as! [String?: Any?]

    return HkSample(
      uuid: uuid,
      type: type,
      startMs: startMs,
      endMs: endMs,
      value: value,
      unit: unit,
      bloodPressure: bloodPressure,
      source: source,
      device: device,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      type,
      startMs,
      endMs,
      value,
      unit,
      bloodPressure,
      source,
      device,
      metadata,
    ]
  }
  static func == (lhs: HkSample, rhs: HkSample) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.uuid, rhs.uuid) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.startMs, rhs.startMs) && MessagesPigeonInternal.deepEquals(lhs.endMs, rhs.endMs) && MessagesPigeonInternal.deepEquals(lhs.value, rhs.value) && MessagesPigeonInternal.deepEquals(lhs.unit, rhs.unit) && MessagesPigeonInternal.deepEquals(lhs.bloodPressure, rhs.bloodPressure) && MessagesPigeonInternal.deepEquals(lhs.source, rhs.source) && MessagesPigeonInternal.deepEquals(lhs.device, rhs.device) && MessagesPigeonInternal.deepEquals(lhs.metadata, rhs.metadata)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HkSample")
    MessagesPigeonInternal.deepHash(value: uuid, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: startMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: endMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: unit, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bloodPressure, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: source, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: device, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: metadata, hasher: &hasher)
  }

  public var description: String {
    return "HkSample(uuid: \(String(describing: uuid)), type: \(String(describing: type)), startMs: \(String(describing: startMs)), endMs: \(String(describing: endMs)), value: \(String(describing: value)), unit: \(String(describing: unit)), bloodPressure: \(String(describing: bloodPressure)), source: \(String(describing: source)), device: \(String(describing: device)), metadata: \(String(describing: metadata)))"
  }
}

/// Deleted object from `deletedObjects` of the anchored query.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HkDeletedObject: Hashable, CustomStringConvertible {
  var uuid: String
  var syncIdentifier: String? = nil
  var syncVersion: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HkDeletedObject? {
    let uuid = pigeonVar_list[0] as! String
    let syncIdentifier: String? = nilOrValue(pigeonVar_list[1])
    let syncVersion: Int64? = nilOrValue(pigeonVar_list[2])

    return HkDeletedObject(
      uuid: uuid,
      syncIdentifier: syncIdentifier,
      syncVersion: syncVersion
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      syncIdentifier,
      syncVersion,
    ]
  }
  static func == (lhs: HkDeletedObject, rhs: HkDeletedObject) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.uuid, rhs.uuid) && MessagesPigeonInternal.deepEquals(lhs.syncIdentifier, rhs.syncIdentifier) && MessagesPigeonInternal.deepEquals(lhs.syncVersion, rhs.syncVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HkDeletedObject")
    MessagesPigeonInternal.deepHash(value: uuid, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: syncIdentifier, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: syncVersion, hasher: &hasher)
  }

  public var description: String {
    return "HkDeletedObject(uuid: \(String(describing: uuid)), syncIdentifier: \(String(describing: syncIdentifier)), syncVersion: \(String(describing: syncVersion)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HkAnchoredQueryRequest: Hashable, CustomStringConvertible {
  var type: String
  /// Base64 of an `HKQueryAnchor` archived with NSKeyedArchiver; null = first run.
  var anchor: String? = nil
  /// Maximum number of samples per call (0 = no limit).
  var limit: Int64
  /// Optional time window on the sample start time, `fromMs` inclusive,
  /// `toMs` exclusive.
  var fromMs: Int64? = nil
  var toMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HkAnchoredQueryRequest? {
    let type = pigeonVar_list[0] as! String
    let anchor: String? = nilOrValue(pigeonVar_list[1])
    let limit = pigeonVar_list[2] as! Int64
    let fromMs: Int64? = nilOrValue(pigeonVar_list[3])
    let toMs: Int64? = nilOrValue(pigeonVar_list[4])

    return HkAnchoredQueryRequest(
      type: type,
      anchor: anchor,
      limit: limit,
      fromMs: fromMs,
      toMs: toMs
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      anchor,
      limit,
      fromMs,
      toMs,
    ]
  }
  static func == (lhs: HkAnchoredQueryRequest, rhs: HkAnchoredQueryRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.anchor, rhs.anchor) && MessagesPigeonInternal.deepEquals(lhs.limit, rhs.limit) && MessagesPigeonInternal.deepEquals(lhs.fromMs, rhs.fromMs) && MessagesPigeonInternal.deepEquals(lhs.toMs, rhs.toMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HkAnchoredQueryRequest")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: anchor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: limit, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fromMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toMs, hasher: &hasher)
  }

  public var description: String {
    return "HkAnchoredQueryRequest(type: \(String(describing: type)), anchor: \(String(describing: anchor)), limit: \(String(describing: limit)), fromMs: \(String(describing: fromMs)), toMs: \(String(describing: toMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HkAnchoredQueryResult: Hashable, CustomStringConvertible {
  var samples: [HkSample]
  var deleted: [HkDeletedObject]
  var nextAnchor: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HkAnchoredQueryResult? {
    let samples = pigeonVar_list[0] as! [HkSample]
    let deleted = pigeonVar_list[1] as! [HkDeletedObject]
    let nextAnchor: String? = nilOrValue(pigeonVar_list[2])

    return HkAnchoredQueryResult(
      samples: samples,
      deleted: deleted,
      nextAnchor: nextAnchor
    )
  }
  func toList() -> [Any?] {
    return [
      samples,
      deleted,
      nextAnchor,
    ]
  }
  static func == (lhs: HkAnchoredQueryResult, rhs: HkAnchoredQueryResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.samples, rhs.samples) && MessagesPigeonInternal.deepEquals(lhs.deleted, rhs.deleted) && MessagesPigeonInternal.deepEquals(lhs.nextAnchor, rhs.nextAnchor)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HkAnchoredQueryResult")
    MessagesPigeonInternal.deepHash(value: samples, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deleted, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nextAnchor, hasher: &hasher)
  }

  public var description: String {
    return "HkAnchoredQueryResult(samples: \(String(describing: samples)), deleted: \(String(describing: deleted)), nextAnchor: \(String(describing: nextAnchor)))"
  }
}

/// Sample to write. For blood pressure set `systolic`/`diastolic` (creates
/// exactly one `HKCorrelation`), otherwise `value`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HkSaveRequest: Hashable, CustomStringConvertible {
  var type: String
  var startMs: Int64
  var endMs: Int64
  var value: Double? = nil
  var systolic: Double? = nil
  var diastolic: Double? = nil
  /// `HKMetadataKeySyncIdentifier`, e.g. `app:<row_id>`. Must not be empty.
  var syncIdentifier: String
  /// `HKMetadataKeySyncVersion` (export version of the row).
  var syncVersion: Int64
  /// `HKMetadataKeyExternalUUID` (row id).
  var externalUuid: String? = nil
  var wasUserEntered: Bool
  var wasTakenInLab: Bool? = nil
  /// IANA time zone for `HKMetadataKeyTimeZone`.
  var timeZone: String? = nil
  /// `HKBloodGlucoseMealTime`: 1 = preprandial, 2 = postprandial.
  var bloodGlucoseMealTime: Int64? = nil
  /// Name of the `HKDevice` attached to the written objects; null = no device.
  var deviceName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HkSaveRequest? {
    let type = pigeonVar_list[0] as! String
    let startMs = pigeonVar_list[1] as! Int64
    let endMs = pigeonVar_list[2] as! Int64
    let value: Double? = nilOrValue(pigeonVar_list[3])
    let systolic: Double? = nilOrValue(pigeonVar_list[4])
    let diastolic: Double? = nilOrValue(pigeonVar_list[5])
    let syncIdentifier = pigeonVar_list[6] as! String
    let syncVersion = pigeonVar_list[7] as! Int64
    let externalUuid: String? = nilOrValue(pigeonVar_list[8])
    let wasUserEntered = pigeonVar_list[9] as! Bool
    let wasTakenInLab: Bool? = nilOrValue(pigeonVar_list[10])
    let timeZone: String? = nilOrValue(pigeonVar_list[11])
    let bloodGlucoseMealTime: Int64? = nilOrValue(pigeonVar_list[12])
    let deviceName: String? = nilOrValue(pigeonVar_list[13])

    return HkSaveRequest(
      type: type,
      startMs: startMs,
      endMs: endMs,
      value: value,
      systolic: systolic,
      diastolic: diastolic,
      syncIdentifier: syncIdentifier,
      syncVersion: syncVersion,
      externalUuid: externalUuid,
      wasUserEntered: wasUserEntered,
      wasTakenInLab: wasTakenInLab,
      timeZone: timeZone,
      bloodGlucoseMealTime: bloodGlucoseMealTime,
      deviceName: deviceName
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      startMs,
      endMs,
      value,
      systolic,
      diastolic,
      syncIdentifier,
      syncVersion,
      externalUuid,
      wasUserEntered,
      wasTakenInLab,
      timeZone,
      bloodGlucoseMealTime,
      deviceName,
    ]
  }
  static func == (lhs: HkSaveRequest, rhs: HkSaveRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.startMs, rhs.startMs) && MessagesPigeonInternal.deepEquals(lhs.endMs, rhs.endMs) && MessagesPigeonInternal.deepEquals(lhs.value, rhs.value) && MessagesPigeonInternal.deepEquals(lhs.systolic, rhs.systolic) && MessagesPigeonInternal.deepEquals(lhs.diastolic, rhs.diastolic) && MessagesPigeonInternal.deepEquals(lhs.syncIdentifier, rhs.syncIdentifier) && MessagesPigeonInternal.deepEquals(lhs.syncVersion, rhs.syncVersion) && MessagesPigeonInternal.deepEquals(lhs.externalUuid, rhs.externalUuid) && MessagesPigeonInternal.deepEquals(lhs.wasUserEntered, rhs.wasUserEntered) && MessagesPigeonInternal.deepEquals(lhs.wasTakenInLab, rhs.wasTakenInLab) && MessagesPigeonInternal.deepEquals(lhs.timeZone, rhs.timeZone) && MessagesPigeonInternal.deepEquals(lhs.bloodGlucoseMealTime, rhs.bloodGlucoseMealTime) && MessagesPigeonInternal.deepEquals(lhs.deviceName, rhs.deviceName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HkSaveRequest")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: startMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: endMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: systolic, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: diastolic, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: syncIdentifier, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: syncVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: externalUuid, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: wasUserEntered, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: wasTakenInLab, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timeZone, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bloodGlucoseMealTime, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deviceName, hasher: &hasher)
  }

  public var description: String {
    return "HkSaveRequest(type: \(String(describing: type)), startMs: \(String(describing: startMs)), endMs: \(String(describing: endMs)), value: \(String(describing: value)), systolic: \(String(describing: systolic)), diastolic: \(String(describing: diastolic)), syncIdentifier: \(String(describing: syncIdentifier)), syncVersion: \(String(describing: syncVersion)), externalUuid: \(String(describing: externalUuid)), wasUserEntered: \(String(describing: wasUserEntered)), wasTakenInLab: \(String(describing: wasTakenInLab)), timeZone: \(String(describing: timeZone)), bloodGlucoseMealTime: \(String(describing: bloodGlucoseMealTime)), deviceName: \(String(describing: deviceName)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HkCharacteristics: Hashable, CustomStringConvertible {
  var birthYear: Int64? = nil
  var birthMonth: Int64? = nil
  var birthDay: Int64? = nil
  /// "female", "male", "other" or null (not set / no permission).
  var biologicalSex: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HkCharacteristics? {
    let birthYear: Int64? = nilOrValue(pigeonVar_list[0])
    let birthMonth: Int64? = nilOrValue(pigeonVar_list[1])
    let birthDay: Int64? = nilOrValue(pigeonVar_list[2])
    let biologicalSex: String? = nilOrValue(pigeonVar_list[3])

    return HkCharacteristics(
      birthYear: birthYear,
      birthMonth: birthMonth,
      birthDay: birthDay,
      biologicalSex: biologicalSex
    )
  }
  func toList() -> [Any?] {
    return [
      birthYear,
      birthMonth,
      birthDay,
      biologicalSex,
    ]
  }
  static func == (lhs: HkCharacteristics, rhs: HkCharacteristics) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.birthYear, rhs.birthYear) && MessagesPigeonInternal.deepEquals(lhs.birthMonth, rhs.birthMonth) && MessagesPigeonInternal.deepEquals(lhs.birthDay, rhs.birthDay) && MessagesPigeonInternal.deepEquals(lhs.biologicalSex, rhs.biologicalSex)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HkCharacteristics")
    MessagesPigeonInternal.deepHash(value: birthYear, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: birthMonth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: birthDay, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: biologicalSex, hasher: &hasher)
  }

  public var description: String {
    return "HkCharacteristics(birthYear: \(String(describing: birthYear)), birthMonth: \(String(describing: birthMonth)), birthDay: \(String(describing: birthDay)), biologicalSex: \(String(describing: biologicalSex)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HkRequestStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HkWriteStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return HkSource.fromList(self.readValue() as! [Any?])
    case 132:
      return HkDevice.fromList(self.readValue() as! [Any?])
    case 133:
      return HkBloodPressure.fromList(self.readValue() as! [Any?])
    case 134:
      return HkSample.fromList(self.readValue() as! [Any?])
    case 135:
      return HkDeletedObject.fromList(self.readValue() as! [Any?])
    case 136:
      return HkAnchoredQueryRequest.fromList(self.readValue() as! [Any?])
    case 137:
      return HkAnchoredQueryResult.fromList(self.readValue() as! [Any?])
    case 138:
      return HkSaveRequest.fromList(self.readValue() as! [Any?])
    case 139:
      return HkCharacteristics.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HkRequestStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? HkWriteStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? HkSource {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? HkDevice {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? HkBloodPressure {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? HkSample {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? HkDeletedObject {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? HkAnchoredQueryRequest {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? HkAnchoredQueryResult {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? HkSaveRequest {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? HkCharacteristics {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AnchoredHealthApi {
  /// `HKHealthStore.isHealthDataAvailable()`.
  func isHealthDataAvailable() throws -> Bool
  /// Platform types supported by the plugin.
  func supportedTypes() throws -> [String]
  /// Fixed unit per type in which `value` is delivered/expected.
  func unitFor(type: String) throws -> String
  /// Whether `requestAuthorization` would still show a dialog for this set.
  func requestStatus(read: [String], write: [String], characteristics: Bool, includeBloodPressureCorrelation: Bool, completion: @escaping (Result<HkRequestStatus, Error>) -> Void)
  /// One dialog for the union of all types. `true` = the dialog ran without
  /// error (says nothing about the granted permissions).
  func requestAuthorization(read: [String], write: [String], characteristics: Bool, includeBloodPressureCorrelation: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Write status per type (read status cannot be queried in HealthKit).
  func writeStatus(type: String) throws -> HkWriteStatus
  func anchoredQuery(request: HkAnchoredQueryRequest, completion: @escaping (Result<HkAnchoredQueryResult, Error>) -> Void)
  /// Saves all samples in one call; returns UUIDs in input order (for blood
  /// pressure the UUID of the correlation).
  func save(samples: [HkSaveRequest], completion: @escaping (Result<[String], Error>) -> Void)
  /// Deletes own objects by UUID; returns the number of deleted objects.
  func delete(type: String, uuids: [String], completion: @escaping (Result<Int64, Error>) -> Void)
  /// Date of birth / biological sex (comparison only, nothing is stored).
  func characteristics() throws -> HkCharacteristics
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AnchoredHealthApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AnchoredHealthApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AnchoredHealthApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// `HKHealthStore.isHealthDataAvailable()`.
    let isHealthDataAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.isHealthDataAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isHealthDataAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isHealthDataAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isHealthDataAvailableChannel.setMessageHandler(nil)
    }
    /// Platform types supported by the plugin.
    let supportedTypesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.supportedTypes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      supportedTypesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.supportedTypes()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      supportedTypesChannel.setMessageHandler(nil)
    }
    /// Fixed unit per type in which `value` is delivered/expected.
    let unitForChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.unitFor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unitForChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! String
        do {
          let result = try api.unitFor(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unitForChannel.setMessageHandler(nil)
    }
    /// Whether `requestAuthorization` would still show a dialog for this set.
    let requestStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.requestStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let readArg = args[0] as! [String]
        let writeArg = args[1] as! [String]
        let characteristicsArg = args[2] as! Bool
        let includeBloodPressureCorrelationArg = args[3] as! Bool
        api.requestStatus(read: readArg, write: writeArg, characteristics: characteristicsArg, includeBloodPressureCorrelation: includeBloodPressureCorrelationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestStatusChannel.setMessageHandler(nil)
    }
    /// One dialog for the union of all types. `true` = the dialog ran without
    /// error (says nothing about the granted permissions).
    let requestAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.requestAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestAuthorizationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let readArg = args[0] as! [String]
        let writeArg = args[1] as! [String]
        let characteristicsArg = args[2] as! Bool
        let includeBloodPressureCorrelationArg = args[3] as! Bool
        api.requestAuthorization(read: readArg, write: writeArg, characteristics: characteristicsArg, includeBloodPressureCorrelation: includeBloodPressureCorrelationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestAuthorizationChannel.setMessageHandler(nil)
    }
    /// Write status per type (read status cannot be queried in HealthKit).
    let writeStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.writeStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! String
        do {
          let result = try api.writeStatus(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      writeStatusChannel.setMessageHandler(nil)
    }
    let anchoredQueryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.anchoredQuery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      anchoredQueryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! HkAnchoredQueryRequest
        api.anchoredQuery(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      anchoredQueryChannel.setMessageHandler(nil)
    }
    /// Saves all samples in one call; returns UUIDs in input order (for blood
    /// pressure the UUID of the correlation).
    let saveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.save\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let samplesArg = args[0] as! [HkSaveRequest]
        api.save(samples: samplesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveChannel.setMessageHandler(nil)
    }
    /// Deletes own objects by UUID; returns the number of deleted objects.
    let deleteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.delete\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! String
        let uuidsArg = args[1] as! [String]
        api.delete(type: typeArg, uuids: uuidsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteChannel.setMessageHandler(nil)
    }
    /// Date of birth / biological sex (comparison only, nothing is stored).
    let characteristicsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.characteristics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      characteristicsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.characteristics()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      characteristicsChannel.setMessageHandler(nil)
    }
  }
}
