// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Result of `getRequestStatusForAuthorization`.
enum HkRequestStatus {
  /// Status unknown (error or not available).
  unknown,
  /// The dialog has never been shown for at least one type.
  shouldRequest,
  /// The dialog has already been shown for all types.
  unnecessary,
}

/// Result of `authorizationStatus(for:)` (only write access can be queried).
enum HkWriteStatus {
  notDetermined,
  sharingDenied,
  sharingAuthorized,
  unknown,
}

/// Source of a sample (`HKSourceRevision`).
class HkSource {
  HkSource({
    required this.bundleId,
    required this.name,
    this.version,
    this.productType,
    this.operatingSystemVersion,
  });

  String bundleId;

  String name;

  String? version;

  String? productType;

  String? operatingSystemVersion;

  List<Object?> _toList() {
    return <Object?>[
      bundleId,
      name,
      version,
      productType,
      operatingSystemVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static HkSource decode(Object result) {
    result as List<Object?>;
    return HkSource(
      bundleId: result[0]! as String,
      name: result[1]! as String,
      version: result[2] as String?,
      productType: result[3] as String?,
      operatingSystemVersion: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HkSource || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(bundleId, other.bundleId) && _deepEquals(name, other.name) && _deepEquals(version, other.version) && _deepEquals(productType, other.productType) && _deepEquals(operatingSystemVersion, other.operatingSystemVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HkSource(bundleId: $bundleId, name: $name, version: $version, productType: $productType, operatingSystemVersion: $operatingSystemVersion)';
  }
}

/// Measuring device (`HKDevice`), all fields optional.
class HkDevice {
  HkDevice({
    this.name,
    this.model,
    this.manufacturer,
    this.hardwareVersion,
    this.firmwareVersion,
    this.softwareVersion,
    this.localIdentifier,
    this.udiDeviceIdentifier,
  });

  String? name;

  String? model;

  String? manufacturer;

  String? hardwareVersion;

  String? firmwareVersion;

  String? softwareVersion;

  String? localIdentifier;

  String? udiDeviceIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      name,
      model,
      manufacturer,
      hardwareVersion,
      firmwareVersion,
      softwareVersion,
      localIdentifier,
      udiDeviceIdentifier,
    ];
  }

  Object encode() {
    return _toList();  }

  static HkDevice decode(Object result) {
    result as List<Object?>;
    return HkDevice(
      name: result[0] as String?,
      model: result[1] as String?,
      manufacturer: result[2] as String?,
      hardwareVersion: result[3] as String?,
      firmwareVersion: result[4] as String?,
      softwareVersion: result[5] as String?,
      localIdentifier: result[6] as String?,
      udiDeviceIdentifier: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HkDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(model, other.model) && _deepEquals(manufacturer, other.manufacturer) && _deepEquals(hardwareVersion, other.hardwareVersion) && _deepEquals(firmwareVersion, other.firmwareVersion) && _deepEquals(softwareVersion, other.softwareVersion) && _deepEquals(localIdentifier, other.localIdentifier) && _deepEquals(udiDeviceIdentifier, other.udiDeviceIdentifier);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HkDevice(name: $name, model: $model, manufacturer: $manufacturer, hardwareVersion: $hardwareVersion, firmwareVersion: $firmwareVersion, softwareVersion: $softwareVersion, localIdentifier: $localIdentifier, udiDeviceIdentifier: $udiDeviceIdentifier)';
  }
}

/// Blood pressure from an `HKCorrelation` (mmHg).
class HkBloodPressure {
  HkBloodPressure({
    required this.systolic,
    required this.diastolic,
    this.systolicUuid,
    this.diastolicUuid,
  });

  double systolic;

  double diastolic;

  String? systolicUuid;

  String? diastolicUuid;

  List<Object?> _toList() {
    return <Object?>[
      systolic,
      diastolic,
      systolicUuid,
      diastolicUuid,
    ];
  }

  Object encode() {
    return _toList();  }

  static HkBloodPressure decode(Object result) {
    result as List<Object?>;
    return HkBloodPressure(
      systolic: result[0]! as double,
      diastolic: result[1]! as double,
      systolicUuid: result[2] as String?,
      diastolicUuid: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HkBloodPressure || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(systolic, other.systolic) && _deepEquals(diastolic, other.diastolic) && _deepEquals(systolicUuid, other.systolicUuid) && _deepEquals(diastolicUuid, other.diastolicUuid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HkBloodPressure(systolic: $systolic, diastolic: $diastolic, systolicUuid: $systolicUuid, diastolicUuid: $diastolicUuid)';
  }
}

/// A sample that was read. For blood pressure, `uuid` is the UUID of the
/// correlation, `value` is null and `bloodPressure` is set.
class HkSample {
  HkSample({
    required this.uuid,
    required this.type,
    required this.startMs,
    required this.endMs,
    this.value,
    this.unit,
    this.bloodPressure,
    required this.source,
    this.device,
    required this.metadata,
  });

  String uuid;

  String type;

  int startMs;

  int endMs;

  /// Value in the fixed plugin unit of the type (see `unit`).
  double? value;

  String? unit;

  HkBloodPressure? bloodPressure;

  HkSource source;

  HkDevice? device;

  /// HealthKit metadata: strings, numbers, bools; dates as ms since epoch,
  /// quantities as text.
  Map<String?, Object?> metadata;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      type,
      startMs,
      endMs,
      value,
      unit,
      bloodPressure,
      source,
      device,
      metadata,
    ];
  }

  Object encode() {
    return _toList();  }

  static HkSample decode(Object result) {
    result as List<Object?>;
    return HkSample(
      uuid: result[0]! as String,
      type: result[1]! as String,
      startMs: result[2]! as int,
      endMs: result[3]! as int,
      value: result[4] as double?,
      unit: result[5] as String?,
      bloodPressure: result[6] as HkBloodPressure?,
      source: result[7]! as HkSource,
      device: result[8] as HkDevice?,
      metadata: (result[9]! as Map<Object?, Object?>).cast<String?, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HkSample || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(type, other.type) && _deepEquals(startMs, other.startMs) && _deepEquals(endMs, other.endMs) && _deepEquals(value, other.value) && _deepEquals(unit, other.unit) && _deepEquals(bloodPressure, other.bloodPressure) && _deepEquals(source, other.source) && _deepEquals(device, other.device) && _deepEquals(metadata, other.metadata);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HkSample(uuid: $uuid, type: $type, startMs: $startMs, endMs: $endMs, value: $value, unit: $unit, bloodPressure: $bloodPressure, source: $source, device: $device, metadata: $metadata)';
  }
}

/// Deleted object from `deletedObjects` of the anchored query.
class HkDeletedObject {
  HkDeletedObject({
    required this.uuid,
    this.syncIdentifier,
    this.syncVersion,
  });

  String uuid;

  String? syncIdentifier;

  int? syncVersion;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      syncIdentifier,
      syncVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static HkDeletedObject decode(Object result) {
    result as List<Object?>;
    return HkDeletedObject(
      uuid: result[0]! as String,
      syncIdentifier: result[1] as String?,
      syncVersion: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HkDeletedObject || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(syncIdentifier, other.syncIdentifier) && _deepEquals(syncVersion, other.syncVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HkDeletedObject(uuid: $uuid, syncIdentifier: $syncIdentifier, syncVersion: $syncVersion)';
  }
}

class HkAnchoredQueryRequest {
  HkAnchoredQueryRequest({
    required this.type,
    this.anchor,
    required this.limit,
    this.fromMs,
    this.toMs,
  });

  String type;

  /// Base64 of an `HKQueryAnchor` archived with NSKeyedArchiver; null = first run.
  String? anchor;

  /// Maximum number of samples per call (0 = no limit).
  int limit;

  /// Optional time window on the sample start time, `fromMs` inclusive,
  /// `toMs` exclusive.
  int? fromMs;

  int? toMs;

  List<Object?> _toList() {
    return <Object?>[
      type,
      anchor,
      limit,
      fromMs,
      toMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static HkAnchoredQueryRequest decode(Object result) {
    result as List<Object?>;
    return HkAnchoredQueryRequest(
      type: result[0]! as String,
      anchor: result[1] as String?,
      limit: result[2]! as int,
      fromMs: result[3] as int?,
      toMs: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HkAnchoredQueryRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(anchor, other.anchor) && _deepEquals(limit, other.limit) && _deepEquals(fromMs, other.fromMs) && _deepEquals(toMs, other.toMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HkAnchoredQueryRequest(type: $type, anchor: $anchor, limit: $limit, fromMs: $fromMs, toMs: $toMs)';
  }
}

class HkAnchoredQueryResult {
  HkAnchoredQueryResult({
    required this.samples,
    required this.deleted,
    this.nextAnchor,
  });

  List<HkSample> samples;

  List<HkDeletedObject> deleted;

  String? nextAnchor;

  List<Object?> _toList() {
    return <Object?>[
      samples,
      deleted,
      nextAnchor,
    ];
  }

  Object encode() {
    return _toList();  }

  static HkAnchoredQueryResult decode(Object result) {
    result as List<Object?>;
    return HkAnchoredQueryResult(
      samples: (result[0]! as List<Object?>).cast<HkSample>(),
      deleted: (result[1]! as List<Object?>).cast<HkDeletedObject>(),
      nextAnchor: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HkAnchoredQueryResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(samples, other.samples) && _deepEquals(deleted, other.deleted) && _deepEquals(nextAnchor, other.nextAnchor);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HkAnchoredQueryResult(samples: $samples, deleted: $deleted, nextAnchor: $nextAnchor)';
  }
}

/// Sample to write. For blood pressure set `systolic`/`diastolic` (creates
/// exactly one `HKCorrelation`), otherwise `value`.
class HkSaveRequest {
  HkSaveRequest({
    required this.type,
    required this.startMs,
    required this.endMs,
    this.value,
    this.systolic,
    this.diastolic,
    required this.syncIdentifier,
    required this.syncVersion,
    this.externalUuid,
    required this.wasUserEntered,
    this.wasTakenInLab,
    this.timeZone,
    this.bloodGlucoseMealTime,
    this.deviceName,
  });

  String type;

  int startMs;

  int endMs;

  double? value;

  double? systolic;

  double? diastolic;

  /// `HKMetadataKeySyncIdentifier`, e.g. `app:<row_id>`. Must not be empty.
  String syncIdentifier;

  /// `HKMetadataKeySyncVersion` (export version of the row).
  int syncVersion;

  /// `HKMetadataKeyExternalUUID` (row id).
  String? externalUuid;

  bool wasUserEntered;

  bool? wasTakenInLab;

  /// IANA time zone for `HKMetadataKeyTimeZone`.
  String? timeZone;

  /// `HKBloodGlucoseMealTime`: 1 = preprandial, 2 = postprandial.
  int? bloodGlucoseMealTime;

  /// Name of the `HKDevice` attached to the written objects; null = no device.
  String? deviceName;

  List<Object?> _toList() {
    return <Object?>[
      type,
      startMs,
      endMs,
      value,
      systolic,
      diastolic,
      syncIdentifier,
      syncVersion,
      externalUuid,
      wasUserEntered,
      wasTakenInLab,
      timeZone,
      bloodGlucoseMealTime,
      deviceName,
    ];
  }

  Object encode() {
    return _toList();  }

  static HkSaveRequest decode(Object result) {
    result as List<Object?>;
    return HkSaveRequest(
      type: result[0]! as String,
      startMs: result[1]! as int,
      endMs: result[2]! as int,
      value: result[3] as double?,
      systolic: result[4] as double?,
      diastolic: result[5] as double?,
      syncIdentifier: result[6]! as String,
      syncVersion: result[7]! as int,
      externalUuid: result[8] as String?,
      wasUserEntered: result[9]! as bool,
      wasTakenInLab: result[10] as bool?,
      timeZone: result[11] as String?,
      bloodGlucoseMealTime: result[12] as int?,
      deviceName: result[13] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HkSaveRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(startMs, other.startMs) && _deepEquals(endMs, other.endMs) && _deepEquals(value, other.value) && _deepEquals(systolic, other.systolic) && _deepEquals(diastolic, other.diastolic) && _deepEquals(syncIdentifier, other.syncIdentifier) && _deepEquals(syncVersion, other.syncVersion) && _deepEquals(externalUuid, other.externalUuid) && _deepEquals(wasUserEntered, other.wasUserEntered) && _deepEquals(wasTakenInLab, other.wasTakenInLab) && _deepEquals(timeZone, other.timeZone) && _deepEquals(bloodGlucoseMealTime, other.bloodGlucoseMealTime) && _deepEquals(deviceName, other.deviceName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HkSaveRequest(type: $type, startMs: $startMs, endMs: $endMs, value: $value, systolic: $systolic, diastolic: $diastolic, syncIdentifier: $syncIdentifier, syncVersion: $syncVersion, externalUuid: $externalUuid, wasUserEntered: $wasUserEntered, wasTakenInLab: $wasTakenInLab, timeZone: $timeZone, bloodGlucoseMealTime: $bloodGlucoseMealTime, deviceName: $deviceName)';
  }
}

class HkCharacteristics {
  HkCharacteristics({
    this.birthYear,
    this.birthMonth,
    this.birthDay,
    this.biologicalSex,
  });

  int? birthYear;

  int? birthMonth;

  int? birthDay;

  /// "female", "male", "other" or null (not set / no permission).
  String? biologicalSex;

  List<Object?> _toList() {
    return <Object?>[
      birthYear,
      birthMonth,
      birthDay,
      biologicalSex,
    ];
  }

  Object encode() {
    return _toList();  }

  static HkCharacteristics decode(Object result) {
    result as List<Object?>;
    return HkCharacteristics(
      birthYear: result[0] as int?,
      birthMonth: result[1] as int?,
      birthDay: result[2] as int?,
      biologicalSex: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HkCharacteristics || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(birthYear, other.birthYear) && _deepEquals(birthMonth, other.birthMonth) && _deepEquals(birthDay, other.birthDay) && _deepEquals(biologicalSex, other.biologicalSex);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HkCharacteristics(birthYear: $birthYear, birthMonth: $birthMonth, birthDay: $birthDay, biologicalSex: $biologicalSex)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is HkRequestStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is HkWriteStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is HkSource) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is HkDevice) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is HkBloodPressure) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is HkSample) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is HkDeletedObject) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is HkAnchoredQueryRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is HkAnchoredQueryResult) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is HkSaveRequest) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is HkCharacteristics) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : HkRequestStatus.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : HkWriteStatus.values[value];
      case 131:
        return HkSource.decode(readValue(buffer)!);
      case 132:
        return HkDevice.decode(readValue(buffer)!);
      case 133:
        return HkBloodPressure.decode(readValue(buffer)!);
      case 134:
        return HkSample.decode(readValue(buffer)!);
      case 135:
        return HkDeletedObject.decode(readValue(buffer)!);
      case 136:
        return HkAnchoredQueryRequest.decode(readValue(buffer)!);
      case 137:
        return HkAnchoredQueryResult.decode(readValue(buffer)!);
      case 138:
        return HkSaveRequest.decode(readValue(buffer)!);
      case 139:
        return HkCharacteristics.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AnchoredHealthApi {
  /// Constructor for [AnchoredHealthApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AnchoredHealthApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// `HKHealthStore.isHealthDataAvailable()`.
  Future<bool> isHealthDataAvailable() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.isHealthDataAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Platform types supported by the plugin.
  Future<List<String>> supportedTypes() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.supportedTypes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Fixed unit per type in which `value` is delivered/expected.
  Future<String> unitFor(String type) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.unitFor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[type]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// Whether `requestAuthorization` would still show a dialog for this set.
  Future<HkRequestStatus> requestStatus(List<String> read, List<String> write, bool characteristics, bool includeBloodPressureCorrelation) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.requestStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[read, write, characteristics, includeBloodPressureCorrelation]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as HkRequestStatus;
  }

  /// One dialog for the union of all types. `true` = the dialog ran without
  /// error (says nothing about the granted permissions).
  Future<bool> requestAuthorization(List<String> read, List<String> write, bool characteristics, bool includeBloodPressureCorrelation) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.requestAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[read, write, characteristics, includeBloodPressureCorrelation]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Write status per type (read status cannot be queried in HealthKit).
  Future<HkWriteStatus> writeStatus(String type) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.writeStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[type]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as HkWriteStatus;
  }

  Future<HkAnchoredQueryResult> anchoredQuery(HkAnchoredQueryRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.anchoredQuery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as HkAnchoredQueryResult;
  }

  /// Saves all samples in one call; returns UUIDs in input order (for blood
  /// pressure the UUID of the correlation).
  Future<List<String>> save(List<HkSaveRequest> samples) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.save$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[samples]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Deletes own objects by UUID; returns the number of deleted objects.
  Future<int> delete(String type, List<String> uuids) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.delete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[type, uuids]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Date of birth / biological sex (comparison only, nothing is stored).
  Future<HkCharacteristics> characteristics() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.anchored_health_native.AnchoredHealthApi.characteristics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as HkCharacteristics;
  }
}
